name: Update auto completion yaml

on:
  push:
   branches:
    - beta-release  # To be moved to 'main'
   paths:
     # Template change
     - "src/autocompletion/templates/*.yaml"
     # GH change
     - ".github/workflows/update_auto_completion.yml"
     - ".github/actions/update-autocompletion/action.yml"
     - ".github/scripts/update_autocompletion.sh"


jobs:
  update_auto_completion_yaml:
    name: update autocompletion yaml
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v2
      # Run autocompletion script
      - id: update_autocompletion
        name: update autocompletion
        run: |
          bash ".github/scripts/update_autocompletion.sh"
      # Commit to github
      - id: commit_configuration_yaml_files
        name: Commit configuration yaml files
        uses: EndBug/add-and-commit@v4
        with:
          add: "src/autocompletion/"
          author_name: "auto-autocompletion-updater"
          message: "Updating autocompletion - (Autogenerated github actions commit)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          branch: beta-release  # To be moved to 'main'