name: Update auto completion yaml

on:
  pull_request_review:
    types:
      - "submitted"
    branches:
      - main
    paths:
      # Template change
      - "src/autocompletion/templates/*.yaml"
      # GH change
      - ".github/workflows/update_auto_completion.yml"
      - ".github/scripts/update_autocompletion.sh"

jobs:
  update_auto_completion_yaml:
    if: github.event.review.state == 'approved'
    name: update autocompletion yaml
    concurrency: git_commits
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v2
      # Run autocompletion script
      - id: update_autocompletion
        name: update autocompletion
        run: |
          docker run \
             --rm \
             --user "$(id -u):$(id -g)" \
             --volume  "$PWD:$PWD" \
             --workdir "$PWD" \
             umccr/appspec:0.006 \
               bash ".github/scripts/update_autocompletion.sh"
      # Commit to github
      - id: commit_configuration_yaml_files
        name: Commit configuration yaml files
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "src/autocompletion/"
          author_name: "auto-autocompletion-updater"
          message: "Updating autocompletion - (Autogenerated github actions commit)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Push config files
      - name: Push code
        id: git_push
        run: |
          # For debugging purposes
          echo "DEBUG: GITHUB_HEAD_REF env var: ${GITHUB_HEAD_REF}" 1>&2

          # Get current branch
          echo "DEBUG: Getting the current branch" 1>&2
          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "DEBUG: Current branch is: ${CURRENT_BRANCH}" 1>&2

          # Pull first - not needed if this is done on non-main branch
          #git pull --rebase origin "${CURRENT_BRANCH}"

          # Just push
          git push