name: Update auto completion yaml

on:
  workflow_dispatch:
  pull_request_review:
    types:
      - "submitted"
    branches:
      - main
    paths:
      # Template change
      - "src/autocompletion/templates/*.yaml"
      # GH change
      - ".github/workflows/update_auto_completion.yml"
      - ".github/scripts/update_autocompletion.sh"

jobs:
  update_auto_completion_yaml:
    if: ${{ github.event.review.state == 'approved' }}
    name: update autocompletion yaml
    concurrency: git_commits
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v2
      # Run autocompletion script
      - id: update_autocompletion
        name: update autocompletion
        run: |
          docker run \
             --rm \
             --user "$(id -u):$(id -g)" \
             --volume  "$PWD:$PWD" \
             --workdir "$PWD" \
             quay.io/alexiswl4/appspec:0.006 \
               bash ".github/scripts/update_autocompletion.sh"
      # Commit to github
      - id: commit_configuration_yaml_files
        name: Commit configuration yaml files
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "src/autocompletion/"
          default_author: github_actions
          message: "Updating autocompletion - (Autogenerated github actions commit)"
          # Don't push, we push manually in the next step if
          push: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Push config files
      - name: Push code
        id: git_push
        if: ${{ steps.commit_configuration_yaml_files.outputs.committed == 'true' }}
        run: |
          # For debugging purposes
          # Get current branch
          echo "DEBUG: Getting the current branch" 1>&2
          echo "DEBUG: The current branch is ${{ github.event.pull_request.head.ref }}"

          CURRENT_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "DEBUG: Current branch is: ${CURRENT_BRANCH}" 1>&2

          # Pull first (might have had another action complete a commit)
          git pull --rebase origin "${CURRENT_BRANCH}"

          # Then push
          git push origin "${CURRENT_BRANCH}"
